# Why studying perception?

>*In chapter 1, you will learn about an insight from robotics that perception is complicated (Moravec's Paradox). Moreover, we will look at the main reason why perception is hard (Poverty of the stimulus).*
   
## A very short review   

### What is perception?

It is pretty hard to determine the defining characteristics of *perception* — which is surprising given that most lectures or textbooks start with a definition of a subject. Of course perception is what we see, hear, smell, taste and feel. This is correct, however, it might be surprising to you that scientists haven't really settled on many very basic questions regarding the nature of perception such as what are the main characteristics of perception? What are the borders between perception and thinking? Can our thoughts influence how we perceive? What are the goals of perception (e.g., providing veridical information/ news about the environment)? These are fundamental questions that keep attracting many scientist and are actively debated.

### What is easy and what is hard?
- Moravec's paradox

### What is the main challenge?
You've just learned that perceiving is effortless for you, but in fact it is a complex task to generate perception. Many neurons in the brain are involved in constructing perception. But why are there so many neurons for perception? What is the problem that these many neurons try to solve? Well, here it is as expressed for vision:

```
There are infinite possible interpretations of the image falling   
onto the back of your eye (i.e., the retinal image).
```

This challenge is so fundamental to the vision sciences, that it got its own name — the poverty of the stimulus problem. It means that the retinal image (i.e., the stimulus) does not provide sufficient information (i.e, the poverty) to allow a single, unambigous interpretation. Sometimes you will read that a problem is under-constrained, or ill-posed, which basically means the same as above. Please note, there is one school of thought — ecological perception — that rejects the idea of a poor visual stimulus. They have some good arguments, but their way of thinking about vision is not really main-stream. For now, we will stick with the idea of ill-posed problems in vision, but keep in mind that vision scientists still argue whether the retinal image is sufficient or insufficient to enable (direct) perception.

Scientists and artists have created tons of examples to demonstrate that multiple (actually infinite) interpretations based on an input are possible. [provide classic example here; maybe make the point that similar examples exist for language -->chomsky]. While these examples may seem artificial, for your visual system the poverty of the stimulus problem concerns any retinal image at any point in time [An ecological psychologist would probably say, these are still very artificial‚]. The problem is particularly obvious when it comes to 3D-vision. We construct a perception of a three-dimensional world based on a two-dimensional retinal image. This three-dimensional world is not present in the retinal image, and must be inferred. We will hear more about this once we address depth perception in a later session. 

But surprisingly, it seems that we all perceive pretty much the same things around us. This is truley remarkable. Imagine you assign many people (across all ages from babies to elderly) a simple math task (let's say what is 100 - 37) that requires some computation/inference. It is reasonable to expect that an average person should be able to solve that easy task. It is also reasonable to expect that quite some people will get the wrong results (nobody is perfect and some people are simply not good in math). Moreover, you don't expect young children — that never got in touch with number >10 — or all elderly to give the correct answer.  So, once you are done collecting the answers of particpants, you will notice a certain distribution of reported results (distributed with some variance around the true result of 63). Vision, in contrast, has to solve an incredibly harder problem and still all our brains seem to arrive at the same conclusion. Impressive, right? This points to rules (or mechanisms) that are hard-wired in the brain and work very reliably. It is vision scientists' goal to identify such rules of vision. This endevear is highly interdisciplinary and includes methods from psychology, neuroscience, medicine, computer science, robotics, physics, mathematics, and philosophy. We will touch upon methods from all these fields and see how they tell us something about perception.

## Excercises

- What do you think are the main goals of perception?
- Reflection: Can you think of sth where understanding perception really helps?
- Find other examples of Moravec's paradox
- Reflect on whether we really understand how playing chess works
- Could you think of sth that is really easy to solve for the mind/brain?
   

## Further material
- Moravec's Paradox and vaccination
- Ned Block
- Gibson's ecological perspective